# Generated by Django 5.1.5 on 2025-02-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
