# Generated by Django 5.1.5 on 2025-02-08 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_email', to='emails.email'),
        ),
    ]
